# Generated by Django 5.0.3 on 2024-03-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sniffersquaredui', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
